tension:
  site_name: Tension Extensions Directory
  site_summary: Blah, Blah, Blah...
  software_name: Tension
  software_summary: Tension is the complete open source commerce solution for Ruby on Rails originally developed by Sean Schofield. It is completely free to use and is licensed under the New BSD License. 
